export enum MethodList {
  GET_COMPANY = 'get_company',
  GET_SERVICES = 'get_services',
  GET_STEP = 'get_step',
  STEP_ONE = 1,
  STEP_TWO = 2,
  STEP_THREE = 3,
  STEP_FOUR = 4,
  CREATE_INSURANCE = 'create',
  GET_POLIS_URL = 'get_polis_url',
  PAM_CHECK = 'pam.check',
  PAM_PREPARE_PAYMENT = 'pam.prepare_pay',
  PAM_CONFIRM_PAYMENT = 'pam.confirm_pay',
  PAM_RESEND_SMS = 'pam.pay_resend_sms',
  PAM_CHECK_PAYMENT_STATUS = 'pam.check_payment',
  PAM_GET_FISCAL_DETAILS = 'pam.get_fiscal_details',
  PAM_PAY_BY_CASH = 'pam.pay_by_cash',
}
